config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  root to: 'rooms#new'
  resources :rooms, only: [:new, :create, :show]

  get"signup",to: "users#new"
  post"signup",to: "users#create"

  get"login",to: "sessions#new"
  post"login",to: "sessions#create"

  delete "logout", to: "sessions#destroy"
end

app/models/app_session.rb
class AppSession < ApplicationRecord
  belongs_to :user

  has_secure_password :token, validations: false

  before_create {
    self.token = self.class.generate_unique_secure_token
  }

  def to_h
    {
      user_id: user.id,
      app_session: id,
      token: self.token
    }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client
  attr_reader :id

  def initialize(id:)
    @id = id
  end

   def to_param
     id
   end
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	attribute :user, :app_session, :organization
end

app/models/listing.rb
class Listing < ApplicationRecord
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, presence: true
  
  scope :ordered, -> { order(id: :desc) }

  has_many :memberships, dependent: :destroy
  has_many :members, through: :memberships, source: :user

end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/room.rb
class Room
  include AccessPolicy

  attr_reader :id

  def initialize(id:)
    @id = id
  end

   def to_param
     id
   end
end

app/models/room/access_policy.rb
module Room::AccessPolicy
	def show?
		true
	end

	def edit?
		organization == Current.organization
	end

	def update?
		organization == Current.organization
	end

	def destroy?
		organization == Current.organization
	end
end

app/models/user.rb
class User < ApplicationRecord
	rolify
	include Authentication

	before_validation :strip_extraneous_spaces

	has_one :membership, dependent: :destroy
	has_one :organization, through: :membership

	validates :name,
		presence: true

	validates :email,
		format: { with: URI::MailTo::EMAIL_REGEXP },
		uniqueness: { case_sensitive: false }

	rolify

private
	def strip_extraneous_spaces
		self.name = self.name&.strip
		self.email = self.email&.strip
	end
end

app/models/user/authentication.rb
module User::Authentication
	extend ActiveSupport::Concern

	included do
		has_secure_password
		validates :password,
			presence: true,
			length: { minimum: 8 }
		
		has_many :app_sessions
	end

	class_methods do
		def create_app_session(email:, password:)
			user = User.authenticate_by(email: email, password: password)
			user.app_sessions.create if user.present?
		end
	end

	def authenticate_app_session(app_session_id, token)
		app_sessions.find(app_session_id).authenticate_token(token)
	rescue ActiveRecord::RecordNotFound
		nil
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Authenticate
	include Authorize
end

app/controllers/concerns/authorize.rb
module Authorize
	extend ActiveSupport::Concern

	included do
		before_action :authorize_resource_access
		rescue_from NotAuthorizedError, with: :render_forbidden_error
	end

	class_methods do
		def skip_authorization(**options)
			skip_before_action :authorize_resource_access, options
		end
	end

private

	def authorize_resource_access
		authorized = authorizable_resource.send("#{params[:action]}?")

		raise NotAuthorizedError unless authorized
	rescue NotImplementedError
		true # If there's no resource, the request is authorized
	end

	def render_forbidden_error
		render file: "#{Rails.root}/public/404.html",
		status: :forbidden,
		layout: false
	end

	def authorizable_resource
		raise NotImplementedError
	end
end

class NotAuthorizedError < StandardError
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  allow_unauthenticated only: :show
  skip_authorization only: [:new, :create]

  def new
  end

  def create
    redirect_to room_path(SecureRandom.uuid)
  end

  def show
    @client = Client.new(id: SecureRandom.uuid)
    cookies.encrypted[:client_id] = @client.id
    @room = Room.new(id: params[:id])
  end

private

  def authorizable_resource
    @listing = Listing.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	skip_authentication only: [:new, :create]

	def new
	end

	def create
		@app_session = User.create_app_session(
			email: login_params[:email],
			password: login_params[:password]
		)

		if @app_session
			log_in(@app_session)
			
			flash[:success] = t(".success")
			redirect_to root_path, status: :see_other
		else
			flash.now[:danger] = t(".incorrect_details")
			render :new, status: :unprocessable_entity
		end
	end

	def destroy
		log_out

		flash[:success] = t(".success")
		redirect_to root_path, status: :see_other
	end

private
	def login_params
		@login_params ||=
		params.require(:user).permit(:email, :password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_authentication only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @organization = Organization.create(members: [@user])
      @app_session = @user.app_sessions.create
      log_in(@app_session)

      redirect_to root_path,
        status: :see_other,
        flash: { success: t(".welcome", name: @user.name) }
    else
      render :new, status: :unprocessable_entity
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title
	return t("app_name") unless content_for?(:title)
	"#{content_for(:title)} | #{t("app_name")}"
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav >
  <div >
    <div>
      <div >
        <button aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div >
        <div>
          <div>
            <%= link_to(t("title"), root_path) %>
          </div>
        </div>
        <div>
          <div>
            <% if Current.user %>
              <div >
                Welcome, <%= Current.user.name %>!
              </div>
              <%= link_to t(".logout"), logout_path, data: {turbo_method: :delete} %>
            <% else %>
              <%= link_to "Sign Up", signup_path %>
              <%= link_to t(".sessions.new.title"), login_path %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_importmap_tags %>
    <%= yield :head %>
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= render "application/flashes" %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/media/_medium.html.erb
<div
  class="medium"
  id="medium_<%= client_id %>"
  data-controller="medium"
  data-room-target="remoteMedium"
>
  <video autoplay playsinline data-medium-target="mediaElement"></video>
</div>